[package]
name = "unwinding_dyn"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
unwinding = { path = "../", features = ["system-alloc", "personality-dummy", "panic-handler-dummy"] }
libc = "0.2"
